### ISSUE TITLE
Is there any more explanation about the procedures?

### ISSUE THREAD

**Issue by guanfaqian** [MinChen00/Graph-Unlearning#1]
Is there any further explanation about the parameters?

I have some questions when I run it, for example, "partition_method" defaults to sage_km, but under this parameter I need to load the model, and I haven't noticed where to train it.

Also, after I change "partition_method" to "random", it runs successfully. At the time of "unlearning", the following error is reported:
Traceback (most recent call last):
  File "/home/gfq/code/privacy/Graph-Unlearning-main/main.py", line 54, in <module>
    main(args, args['exp'])
  File "/home/gfq/code/privacy/Graph-Unlearning-main/main.py", line 42, in main
    ExpUnlearning(args)
  File "/home/gfq/code/privacy/Graph-Unlearning-main/exp/exp_unlearning.py", line 32, in __init__
    self.train_target_models(run)
  File "/home/gfq/code/privacy/Graph-Unlearning-main/exp/exp_unlearning.py", line 74, in train_target_models
    for shard in range(self.num_shards):
AttributeError: 'ExpUnlearning' object has no attribute 'num_shards'

**Comment by guanfaqian** [comment]
pickle.dump(lpa_deltas, open(config.ANALYSIS_PATH + "partition/base_blpa_" + self.args['dataset_name'], 'wb'))
FileNotFoundError: [Errno 2] No such file or directory: 'temp_data/analysis_data/partition/base_blpa_citeseer'

Does this need to be created on its own or is there a file to run first?

**Comment by MinChen00** [comment]
Hi, thanks for the information. 

I have fixed the issue in `exp_unlearning.py`. `num_shards` is a parameter passed from the `parameter_parser.py` file, all the `self.num_shards` should be `self.args['num_shards']`.

For the second question, yes, some directories need to be created to save the partition data and trained models. The details can be found in `config.py` file.

**Comment by guanfaqian** [comment]
File "/home/gfq/code/privacy/Graph-Unlearning-main/exp/exp_attack_unlearning.py", line 166, in attack_graph_unlearning
    with open(config.MODEL_PATH + self.args['dataset_name'] + "/" + self.args['target_model'] +"_unlearned_indices") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'temp_data/models/citeseer/GAT_unlearned_indices'

where '--exp' is 'attack_unlearning', what are the parameters under which this file was created?

**Comment by liiiyi** [comment]
How did you solve the problem that the files that need to be loaded are missing? I also encountered the same problem, but I didn't find a way to generate these files.
