### ISSUE TITLE
Run FileNotFoundError

### ISSUE THREAD

**Issue by guanfaqian** [MinChen00/Graph-Unlearning#2]
File "/home/gfq/code/privacy/Graph-Unlearning-main/exp/exp_attack_unlearning.py", line 166, in attack_graph_unlearning
with open(config.MODEL_PATH + self.args['dataset_name'] + "/" + self.args['target_model'] +"_unlearned_indices") as file:
FileNotFoundError: [Errno 2] No such file or directory: 'temp_data/models/citeseer/GAT_unlearned_indices'

I am experimenting under  '--exp' is 'attack_unlearning', what are the parameters under which this file was created?

**Comment by guanfaqian** [comment]
In exp_attack_unlearning.py
    
def graph_unlearning_request_respond(self, node_unlearning_request=None):
        # reindex the node ids
        node_to_com = self.data_estore.c2n_to_n2c(self.community_to_node)

"self.data_estore" no find, is "self.data_store"?

**Comment by MinChen00** [comment]
Hi, for the first question, it seems you did not save the unlearned indices correctly. When you meet the FileNotFoundError, please first consider checking whether you indeed created that file.

For the second question, you're right. We define `data_store` to deal with storage-related functions. However, I do not find this typo in my original code. Would you please double-check your local code?
